#pragma once

namespace Toshi {

	class TFileLexer
	{
	public:
		enum TokenType {
			TOKEN_UNKNOWN,
			TOKEN_SEMI,
			TOKEN_COLON,
			TOKEN_COMMA,
			TOKEN_DOT,
			TOKEN_ASTERISK,
			TOKEN_DOLLAR,
			TOKEN_OPENSQR,
			TOKEN_CLOSESQR,
			TOKEN_OPENBRACE,
			TOKEN_CLOSEBRACE,
			TOKEN_OPENPAREN,
			TOKEN_CLOSEPAREN,
			TOKEN_LESSTHAN,
			TOKEN_GREATERTHAN,
			TOKEN_EQUAL,
			TOKEN_IDENT = 16,
			TOKEN_STRING = 17,
			TOKEN_INTEGER = 18,
			TOKEN_UINTEGER = 19,
			TOKEN_FLOAT = 20,
			TOKEN_COMMENT = 21,
		};

	};

}