#pragma once

namespace Toshi {

	namespace TFileLexer
	{
		enum TokenType {
			TOKEN_UNKNOWN,
			TOKEN_SEMI,
			TOKEN_COLON,
			TOKEN_COMMA,
			TOKEN_DOT,
			TOKEN_ASTERISK,
			TOKEN_DOLLAR,
			TOKEN_OPENSQR,
			TOKEN_CLOSESQR,
			TOKEN_OPENBRACE,
			TOKEN_CLOSEBRACE,
			TOKEN_OPENPAREN,
			TOKEN_CLOSEPAREN,
			TOKEN_LESSTHAN,
			TOKEN_GREATERTHAN,
			TOKEN_EQUAL,
			TOKEN_IDENT,
			TOKEN_STRING,
			TOKEN_INTEGER,
			TOKEN_UINTEGER,
			TOKEN_FLOAT,
			TOKEN_COMMENT,
		};
	}

}